### PR TITLE
Close #189 and #191

### LINKED ISSUE #189: Gulp Build Issue
First, thanks for this awesome directive. I'm having an issue with it the gulp build on the server. The angular-tooltips.css file is trying to map to \angular-material\angular-tooltips.css.map.

### PR DESCRIPTION
**Pull request by simonepri**
This PR fix these:
https://github.com/720kb/angular-tooltips/issues/191
https://github.com/720kb/angular-tooltips/issues/189

### CODE REVIEW

**Comment by 45kb** [comment]
@simonepri Hey! thanks a lot for this. Have you tested all and it's all working correct?

Just curious but why does removing this line ` unregisterOnTooltipControllerChange();` ?  :)

**Comment by simonepri** [comment]
Sorry @45kb it was an error. I've just re-added it
Yes everything seems ok now.

**Comment by 45kb** [comment]
cool @simonepri thanks a lot! seriously appreciated 💯

**Comment by 45kb** [comment]
you can now update the lib to 1.1.9 👍

**Pull request merged**
