### PR TITLE
Use !default to declare SCSS variables & make font-sizes configurable

### PR DESCRIPTION
**Pull request by jogjayr**
1. Declare all SCSS vars as !default so that they can be overridden by users wanting different settings
2. Declare font sizes with variables so that they can be configured also

https://github.com/720kb/angular-tooltips/issues/177

### CODE REVIEW

**Comment by willsoto-FD** [comment]
Would love to see this land. Anything else that is needed for this?

**Comment by jogjayr** [comment]
@45kb do you need anything else from me? It would be great if you could merge this in so I don't have to continue to maintain my own fork. There's no functionality/logical changes at all; in theory nothing should work differently for other users.

**Comment by 45kb** [comment]
Hi @jogjayr sorry for the delay, i am going to merge this, looks really ok, thank you for your help 👍

**Comment by 45kb** [comment]
shipd :package: https://github.com/720kb/angular-tooltips/releases/tag/1.1.7

**Comment by jogjayr** [comment]
Thanks @45kb

**Pull request merged**
