### PR TITLE
Fix the empty tooltip verification

### PR DESCRIPTION
**Pull request by panzerdp**
Related to: https://github.com/720kb/angular-tooltips/issues/97

### CODE REVIEW

**Comment by panzerdp** [comment]
And if it would be possible to access data in template view, that would be just great. :)
Thanks.

**Comment by wouldgo** [comment]
Hi @panzerdp,

could you explain us the usage of scope variable tooltipViewModel?
Thanks for your contribution.

**Comment by panzerdp** [comment]
Hi @wouldgo,

I use tooltipViewModel to display data in the tooltip template. For example:
1) The code in controller:
```javascript
function MyCtrl() {
  //controller
  $scope.user = {
     name: 'John Smith',
     email: 'john@mail.com'
  }
}
```
2) The controller template:
```html
<a href="#" tooltips tooltip-view="tooltip.html" tooltip-view-model="user"/>
```
3) The tooltip template:
```html
<!-- tooltip.html -->
<span>Hello {{ tooltipViewModel.name }}, with email {{ tooltipViewModel.email }}</span>
```

I hope it is clear now.
Thanks!

**Comment by wouldgo** [comment]
Sorry for my "slowness", now it's clear as clear water!

Only one little thing right before merge: could you please explain the tooltipViewModel usage in README.md in the options section?

Thanks again.
Dario

**Comment by panzerdp** [comment]
Updated.
Let me know if the explanation is clear enough.

Thank you.

**Comment by wouldgo** [comment]
Good, 

Thank you for your time.
Closing also #97.

Have a good day,
Dario

**Comment by panzerdp** [comment]
Thanks Dario.
When do you plan to release a new version? Especially on npm.

**Comment by panzerdp** [comment]
Ah, could you update the Readme from this:
```html
<!-- path/to/view.html -->
<span>Tooltip me with data - {{ tooltipViewModel.myModel }}</span>
```
to this:
```html
<!-- path/to/view.html -->
<span>Tooltip me with data - {{ tooltipViewModel }}</span>
```
No need for myModel in the template. Sorry for the typo :).

**Comment by wouldgo** [comment]
done [here](https://github.com/720kb/angular-tooltips/blob/master/Readme.md#tooltip-view-model).

As far as I reach my home computer I could manage a new version deploy.

**Comment by 45kb** [comment]
@panzerdp thank you for your time, great job !

**Comment by panzerdp** [comment]
Thanks @45kb 
I'm happy to contribute, because the module is great.

**Comment by 45kb** [comment]
@panzerdp thank you a lot, this is an awesome job, the problem is deeper but i appreciated a lot :+1:

**Comment by panzerdp** [comment]
@45kb 
"The problem is deeper": do you mean that the empty verification is not well enough? I agree because it is a complex thing to verify if the included template has an empty content.

**Comment by 45kb** [comment]
What i mean is that, due to past mistakes, the module is setting visiblity via javascript (is not your fault but our fault), so, to fix the problem at all we need to absolutely avoid manipulating css via javascript :)

**Comment by panzerdp** [comment]
@45kb 
How do you plan to update that? Anyway you need using javascript to update the tooltip visibility. But at least you should have a special class for that (but I think there is already `_720kb-tooltip-open`).
Thanks.

**Comment by 45kb** [comment]
Exactly, we need only css classes, no need to add or remove css rules from js ;)

The plan is exactly this, remove any css rule invocation from js :+1:

**Comment by panzerdp** [comment]
Yep. I think the best would be to remove at all the css classes and styles from javascript directive code to a `$scope.tooltipVisible`. The angular's ng-class should take care of handling the classes for tooltip DOM element.

**Comment by 45kb** [comment]
@panzerdp OMG, i am sorry i was talking about the other PR (https://github.com/720kb/angular-tooltips/pull/99) :/ big sorry

**Comment by panzerdp** [comment]
@45kb No problem :D

**Comment by 45kb** [comment]
I really have no words, sorry  :dancers:

**Pull request merged**
