### PR TITLE
Adds template URL caching as attribute option

### PR DESCRIPTION
**Pull request by kmoroder**

### CODE REVIEW

**Comment by 45kb** [comment]
Hi @kmoroder impressive!

Thank you, because this is what we were expecting as caching option 👍 

Going to merge and release a new version of the module.

**Comment by 45kb** [comment]
Just, next time, use lib/ files to PR changes 

dist/ folder is the production one 👍

**Comment by 45kb** [comment]
Ok, now this option is available with the new `1.1.5` version of the module.

Can you please try it and feedback if anything not working yet?

Thanks, see this line note https://github.com/720kb/angular-tooltips/commit/e9751f721403be0170b565ece9c95935c7557640

**Comment by kmoroder** [comment]
@45kb Not working yet - wondering if I missed something in the logic. Maybe in line 582, adding `!$attrs.tooltipTemplateUrlCache` (see below)?

I'll keep trying to troubleshoot - but if you figure it out, please let me know!

`          , onTooltipTemplateUrlChange = function onTooltipTemplateUrlChange(newValue) {
            if (newValue && !$attrs.tooltipTemplateUrlCache) {`

**Comment by 45kb** [comment]
Thank you @kmoroder  your fix now comes with the newest `1.1.6« version of the module

**Pull request merged**
