### PR TITLE
Add support for corner positions.

### LINKED ISSUE #205: Support corner positions
Support for corner positions (`top left`, `top right`, `bottom left`, `bottom right`) would be useful, particularly for elements (that are positioned near corners) with large tooltips.

Consider the following screenshot as an example. Clicking on the smiley face opens up a tooltip containing a menu. The menu only manages to be partially rendered in the window. The same would apply to any of the cardinal directions. Being able to position it `top left` would allow it to be fully rendered on screen. 

_Please ignore the separate issue I'm having where all items in a tooltip that have tooltips all show their tooltips regardless of their trigger event._

scrubby_2017-05-19_14-53-38

### PR DESCRIPTION
**Pull request by leonard-thieu**
Fixes #205 

This PR adds support for corner positions (`top left`, `top right`, `bottom left`, `bottom right`). This also modifies the `smart` option to include the corner position as candidates. However, it appears the `smart` algorithm doesn't work correctly even in the most recent commit (44da315a24451b04b2d59d38569c1f9f20e4b436). I believe this also fixes a bug with `onTooltipSideChange` where it may have failed to remove the old attribute.

Also, I didn't know what to do with the tip arrows. They ended up looking pretty ugly.

### CODE REVIEW

**Comment by 45kb** [comment]
@leonard-thieu tried it and it's working ! Just i can't see the tip arrow showing up can you adjust it before to merge ?

thanks :)

**Comment by leonard-thieu** [comment]
> :not() looks not widely supported http://caniuse.com/#search=%3Anot

That's for the selector list argument. I'm only using single simple selectors.

- http://caniuse.com/#feat=css-sel3
- https://developer.mozilla.org/en-US/docs/Web/CSS/:not#Browser_compatibility

> The tip arrow is not showing up

I'm not sure why the tip arrow is not showing up for you (or why the tooltip isn't positioned correctly). I can't reproduce it. This is how it displays for me: 

corner-positions-browsers

**Comment by leonard-thieu** [comment]
Also, I'm thinking I should change the order of the directions that the `smart` algorithm iterates through. Originally, `smart` selected counter-clockwise from the start direction (except for `bottom` for which it went clockwise). I tried to keep some backwards-compatibility by having it try cardinal directions first but I didn't implement it correctly (and it wouldn't work for `bottom` anyway).

I think it might make more sense to have it cycle through all directions in order (i.e. `top` -> `top left` -> `left` -> `bottom left`). This should result in it selecting a position closer to the start position and take less iterations to find a position.

**Comment by 45kb** [comment]
> That's for the selector list argument. I'm only using single simple selectors.
You're right sorry i found the wrong :not()

> I'm not sure why the tip arrow is not showing up for you (or why the tooltip isn't positioned correctly). I can't reproduce it.

Now it works also for me, i cloned your fork https://github.com/leonard-thieu/angular-tooltips and checkedout the corner-positioins branch, everythings ok now :)

So let me know how you want to proceed for the directions order, if to open a new PR and merge this or if to wait a little, no problems ...

**Comment by leonard-thieu** [comment]
I'll just make the change now since it hasn't been merged yet.

**Comment by leonard-thieu** [comment]
This should be good to go.

**Comment by 45kb** [comment]
@leonard-thieu tried it locally https://github.com/leonard-thieu/angular-tooltips/tree/corner-positions

but it doesn't seems to work, can you have a look and let me know?

thank you.

**Comment by leonard-thieu** [comment]
angularjs_tooltips_-_google_chrome_2017-05-21_08-26-23
I can't reproduce and I'm not sure why it's positioning `top` instead of `top left` for you.

**Comment by 45kb** [comment]
@leonard-thieu sorry my bad this was the problem https://github.com/720kb/angular-tooltips/blob/master/index.html#L359 :) must be src/ not dist/ thanks for this great addition, i am going to release it

**Comment by 45kb** [comment]
shipped 📦  https://github.com/720kb/angular-tooltips/releases/tag/1.2.0

**Pull request merged**
