### PR TITLE
Dynamic title/content

### LINKED ISSUE #23: $observe for title and content
Need to $observe tooltip-title="" and tooltip-content for changes

### PR DESCRIPTION
**Pull request by marudor**
Using two way binding to watch for changes to title or content.
Also re-inits the tooltip to fix positioning.
Fixes #23 
Requires Angular 1.3 > due to $watchGroups.
Also removes the feature to just use the title attribute.
Only works with tooltip-title and tooltip-content

### CODE REVIEW

**Comment by 45kb** [comment]
@marudor  hi, first of all thanks for the PR, help is always appreciated!

I didn't had any chance to try your changes yet, but having a quick look it seems to me that is no more possible to use html inside both tooltip-title and tooltip-content attributes...

Am i mistaking?

**Comment by marudor** [comment]
You are correct. Let me change it. I've used ng-bind. Just changing it to ng-bind-html should do the trick.
Just did not think about it.

**Comment by marudor** [comment]
Works for HTML as well now.
Does need ngSanitize for safe HTML usage though

**Comment by 45kb** [comment]
@marudor  Hi man, sorry for the delay, actually you did an awesome job but, really, ngSanitize is not needed, the aim is to release an indipendent so 0 dependencies module.

Thanks for your time

**Comment by marudor** [comment]
Well in that case you could assume valid HTML and mark it safe with $sce.
That way it is still possible to use ng-bind-html without ng-sanitize.
I would detect ng-sanitize though as it is way safer to use sanitize for html Content

**Comment by 45kb** [comment]
@marudor i think you are making it more complicated than it really is :)

You can easily watch for vars and put back vars into template  see how it was before was ok: https://github.com/720kb/angular-tooltips/pull/24/files#diff-5e88dc350115fec0d8c52d150ba8b8f7L42

Don't remove that vars just watch for them to change ;)

**Comment by 45kb** [comment]
So just an example (probably not working):

  $scope.$observe(['tooltipTitle'], function(newValue, oldValue) {
   if (newValue) {
    title = newValue; 
   }
   });

**Comment by rupakg** [comment]
@marudor This is exactly the issue I have been struggling with and I happened to stumble upon the PR. I would be glad to help, if you need it. Thanks for putting up the fix.

**Comment by marudor** [comment]
There you go.
If ngSanitize is available it will use it and not fall back to $sce.
If it is not available it will just mark the content and title as trusted.
This is slightly dangeours though. If someone fills tooltipContent or title with user input it should not be used without ngSanitize.

**Comment by rupakg** [comment]
@marudor Thanks a lot for working it so quickly. I already use ```ngSanitize``` so it will be ok for me. I will test it out. I will be using your commit till this gets merged.

@45kb if you guys can review and merge, that would be awesome.

**Comment by rupakg** [comment]
@marudor While testing I found that just plain static text in the ```tooltip-content``` or ```tooltip-title``` does not work anymore, as angular wants to eval the value, like so:

```tooltip-content="this is a very long text that i want to show."```

while dynamic content works fine.

```tooltip-content="tooltip()"```

Can you verify that?

**Comment by marudor** [comment]
You have to wrap it as string.
So 
` tooltip-content="'this is a very long text that i want to show'" `
works.
For added performance do `tootlip-content="::'this is a very long text that i want to show'"`
The :: makes it one time. So no watching for the two way binding.

**Comment by rupakg** [comment]
@marudor cool. interesting comment about the ```::```. Thanks again.

**Comment by bubbleheadinc** [comment]
@marudor How about when using markup and binding?  This used to work before changes:
```
tooltip-content="<div>Account: {{account.name}}</div><div>{{account.type | capitalize}}: {{account.status}}</div>"
```
I am using ngSantize. I tried with the single quotes as you suggested above and I've also tried with ng-bind on spans instead of expression.

Thanks for any help!

**Comment by marudor** [comment]
For that I will probably need to adjust it a little.
I'm not recompiling the input. So it will not work for mixed static and angular expressions.
I would need to set the content to
`$compile(tooltipContent)($scope)`
Will make a commit and comment this evening when I am back from work.

**Comment by 45kb** [comment]
@marudor  thank you for the time you are spending on this! :+1:

**Comment by bubbleheadinc** [comment]
@marudor Sounds great. What about templates with Angular template or templateURL? Maybe that would be a better way to deal with it? I'm a bit of an Angular n00b, though.

**Comment by rupakg** [comment]
sounds a little over kill for using an Angular template for a tooltip!

**Comment by bubbleheadinc** [comment]
Yeah, I guess so. Just seems a bit clunky to me to have to declare the markup for tooltip-content over and over again for each tooltip if you don't want to use the default structure. Either way, the $compile(tooltipContent)($scope) fix @marudor is making would help a ton.

**Comment by wouldgo** [comment]
Hi @marudor,

I've reviewed the diffs in this PR. It's seems legit to me to merge the actual commits, we need only one last thing: could you please update the README.md integrating the you intervents?

Thanks a lot for your commitment and contribution!

Dario

**Comment by 45kb** [comment]
@marudor @bubbleheadinc @marudor  Sorry, i don't quite understand the discussion but (just guessing) is having the possibility to inject html templates inside tooltip-content="" and tooltip-title="" what you are discussing for?

Cause in such case, cound't be better a new attribute, for example tooltip-template="" ?

**Comment by bubbleheadinc** [comment]
@45kb Yes, I was suggesting a template instead of -content so as to more easily manage any custom structure. Unfortunately I don't have the knowledge to code it, but it seems to me another attribute would work well if anyone was willing to put it together.

**Comment by rupakg** [comment]
@marudor @45kb any chance this PR could be rebased and merged. I would really appreciate it.

**Comment by 45kb** [comment]
@rupakg  we would @marudor  to finish pushing changes, he just need to pull all the new changes from the master and commit.

Actually you can use his changes from here https://github.com/marudor/angular-tooltips

**Comment by rupakg** [comment]
@45kb actually we are using @marudor 's fork, but it is ~16 commits behind upstream.

**Comment by rupakg** [comment]
@marudor absolutely, no hurries at all. And, I appreciate all your hard work. /cc @45kb

**Comment by 45kb** [comment]
@rupakg no problems at all :+1:

**Comment by 45kb** [comment]
Hi all, we just merged a new PR for dynamic content and title feel free to try it https://github.com/720kb/angular-tooltips/pull/37

Now the only thing missing is ngSanitize on them...

I am going to remove this PR but, seriously, feel free to open another one if necessary!

Thanks a lot to everyone.

**Pull request closed without merging**
