### PR TITLE
Fix: little modification

### PR DESCRIPTION
**Pull request by KynoYang**
@45kb, hi,  I just did some little modification. I checked the three examples, they work well :)

### CODE REVIEW

**Comment by 45kb** [comment]
@KynoYang  Hey thank you Kyno, if you want we can keep in touch more easily, just send me an email info [at] 720kb.net, i really appreciated your work!

**Comment by KynoYang** [comment]
@45kb Very glad to hear that, thank you. :)

**Comment by 45kb** [comment]
@KynoYang  jump aboard :) we are working on many projects and new ideas, most of them are totally open source, we can learn from each other, i'll explain you where we going via email or just pass me your contact/email ;)

**Comment by KynoYang** [comment]
@45kb No problem. My email is kyno.yang [at] gmail.com.

**Comment by 45kb** [comment]
@KynoYang awesome, i added you on google hangouts, and sent you an email from 720kb.net just in case you don't use hangouts ;)

**Pull request merged**
