### PR TITLE
Throw exception when invalid argument is being passed to the directive

### PR DESCRIPTION
**Pull request by weijye91**
The tooltip won't show up if some of the options passed the attribute is invalid and there is no error thrown in the console. Added some code to validate the value passed to the attribute tooltipSize and tooltipSide.

### CODE REVIEW

**Comment by 45kb** [comment]
Hi @weijye91  thank you for the great job, for me this code is ok, i ping @wouldgo  for a better review.

Thanks :)

**Comment by weijye91** [comment]
Also, if you have no plan to support IE version < 9, why not use the native way of registering and remove events (.addEventListener & .removeEventListener). More info - https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Why_use_addEventListener

**Comment by wouldgo** [comment]
Hi @weijye91,

we know about the `add/removeEventListener` methods provided by modern browsers but, since we are in an angular context and the framework (in the 1.x version) provides the jqLite implementation we decided to use it. So we prefer to mantain the `bind/unbind` methods.
The param check is legit to merge.

In order to merge this, could you please reset to the `474f2a1` commit?

Thank you for you contribution.
Have an awesome day,

Dario

**Comment by weijye91** [comment]
Done.

**Comment by wouldgo** [comment]
Hi @weijye91,

sorry for the delay we were busy this week, merging.

Thanks
Dario

**Pull request merged**
