### PR TITLE
Modify: make title and content dynamic

### PR DESCRIPTION
**Pull request by KynoYang**
@45kb Not the best way, but the easiest.

### CODE REVIEW

**Comment by 45kb** [comment]
Thanks @KynoYang  just going to comment something out before to merge we need some fixs

**Comment by 45kb** [comment]
One more thing, be sure to test it deeply if you can, for example by the controller you could have many scenarios:

$scope.tooltipTitle = 'Hello';

   $timeout(function () {
   $scope.tooltipTitle = 'hey';
   }, 5000);

   $interval(function () {
   $scope.tooltipTitle = Math.random(0, 2828282828);
   }, 2000);

   $http().then(function (response) {
   $scope.tooltipTitle = response.data;
   });

etc ...

**Comment by KynoYang** [comment]
@45kb $interval is used for test. I forgot to remove it.

**Comment by KynoYang** [comment]
@45kb Yeah, there is some work need to do.
 I just read the doc of angularjs about $observe. It may be better than watch. Thank you for your suggestion.

I'll modify it later.

**Comment by KynoYang** [comment]
Hi @45kb.  Is there any thing I should have thought about in this pr, please let me know. I'll fix it ASAP.

**Comment by 45kb** [comment]
@KynoYang  awesome thank you Kyno, and about empty text could be great if you PR that too, yes! :+1:

**Pull request merged**
