### PR TITLE
Keeping tooltip positioning in track with element

### PR DESCRIPTION
**Pull request by hpeinar**
Implemented element position tracing so tooltip can be placed correctly even in scrollable area

### CODE REVIEW

**Comment by 45kb** [comment]
Hi @hpeinar  looks everything working, i've tested it.

Actually using $interval is really not a good practice also if i guess there are not so many alternatives.... maybe requestAnimationFrame, but looping everytime to find position is really heavy, specially if you have 10/20 tooltips in page.

Better to ping @wouldgo  on this, since he is more experienced than me.

**Comment by hpeinar** [comment]
To avoid performance issues, it'd be better to have this either under an option or just working with strict sets of tooltips (only the ones that do not automatically closed on MouseOut for an example).

As we previously talked on gitter, there aren't many other options we have to do this. Only polling the getBoundClientRect shouldn't be a problem performance wise, even if done on 100 elements as the real tooltip repositioning only happens when the element has actually moved.

**Comment by 45kb** [comment]
@hpeinar So we've discussed about this with @wouldgo  and we agree with you, the best way is to set this up with a new attribute ```tooltip-scroll=""``` which by default is FALSE but whenever the user wants can be turned TRUE.

Ok? :+1:

**Comment by wouldgo** [comment]
Hi guys,
saw the PR and the use of $interval. @hpeinar your're right about the polling in this scenario.

**Comment by hpeinar** [comment]
Sounds like a plan. I'll include necessary functionality to the branch asap for the attribute support (Won't probably make to it today).

**Comment by 45kb** [comment]
@hpeinar Thank you, this is an awesome thing you are introducing!

**Comment by hpeinar** [comment]
The tooltip positioning check is now off by default. Can be enabled via tooltip-scroll attr like @wouldgo suggested. I also changed the check interval to 20ms to be smoother and wrote a small readme entry (I'm not so good at these, so feel free to change that).

**Comment by 45kb** [comment]
Awesome @hpeinar  we will release a new version shortly.

Thank you a lot, much appreciated :+1:

**Comment by wouldgo** [comment]
thanks a lot.

**Pull request merged**
