### PR TITLE
feat(commonJS): Now supports CommonJS builds such as Browserify.

### PR DESCRIPTION
**Pull request by mchambaud**

### CODE REVIEW

**Comment by 45kb** [comment]
Hi @mchambaud  thank you for the PR much appreciated, i refer this to @wouldgo  he more experienced than me for this.

**Comment by mchambaud** [comment]
@45kb No problem. 

Any plans of merging this anytime soon? Would love to ditch the shims I have in place.

**Comment by 45kb** [comment]
@mchambaud  i don't know at the moment, it's better to wait for @wouldgo  :+1:

**Comment by wouldgo** [comment]
Hi @mchambaud,

sorry but atm I'm quite full of woking activities. Anyhow your PR is good. Just one thing before accepting it: why do you require the unminified version of the library instead of the minified one?

Thanks
Dario

**Comment by mchambaud** [comment]
@wouldgo there is no reason to have a minified version of a library in a CommonJS build. The build system, will generate a build for debug or production with appropriate minification, obfuscation and maps when require.

**Comment by wouldgo** [comment]
@mchambaud thanks for explanation due I never used browserify and tool like that. Merged, going to publish rigth now.

Best regards

**Comment by mchambaud** [comment]
@wouldgo Awesome THANKS!

**Pull request merged**
